### ISSUE TITLE
Timezone (?) Issue on Selecting Date Range

### ISSUE THREAD

**Issue by bquay** [redpangilinan/iotawise#6]
Hey! I noticed there is a timezone issue when creating Activity Logs. When creating a log, it is automatically adding the user's Timezone (I am in EST, GMT-5)

<img width="1722" alt="Screenshot 2023-12-13 at 7 50 34 PM" src="https://github.com/redpangilinan/iotawise/assets/8851809/f0ad0b54-4d56-4870-a453-35ebca4fd5b6">

This creates an issue when the user selects a date range. When selected, the range does not include a timezone so the logs on the last day of the range are not included in subsequent results. When manually updating the `"to"` date in the URL to include a time later than the timezone offset, the user will see the correct results. 

https://github.com/redpangilinan/iotawise/assets/8851809/7ccaf1d6-d97a-429b-b3d9-9a3428e3117e

**Comment by bquay** [comment]
**UPDATE:**
Given that when I manually set the time to the GMT-EST Timezone offset it provides the correct date I believe we can conclude it's the first possibility

https://github.com/redpangilinan/iotawise/assets/8851809/922dfdf6-3ae7-4c66-81f7-196ee39c8b63

**Comment by redpangilinan** [comment]
I made a quick fix by converting the dates into UTC before querying the database when filtering dates. The issue should be resolved by now.

See aeb31f8 for more info.

**Comment by redpangilinan** [comment]
Re-opening because the fix is not working in production environment. I'll look more into this issue later.

**Comment by redpangilinan** [comment]
Fixed the issue by changing the URL params into UTC date format. Turns out the dates are not being converted properly because they're being converted in server, not client. I can't find a way to retain the cleaner date params then converting them in client since the whole process is happening server side, so UTC date format in params will do.

Since the dates being taken from params are now UTC format, there shouldn't be timezone issues anymore.
